// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	models "github.com/SerafimKuzmin/sd/src/models"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryI is an autogenerated mock type for the RepositoryI type
type RepositoryI struct {
	mock.Mock
}

// CreateEntryPersonalRatings provides a mock function with given fields: entryID, PersonalRatingList
func (_m *RepositoryI) CreateEntryPersonalRatings(entryID uint64, PersonalRatingList []models.PersonalRating) error {
	ret := _m.Called(entryID, PersonalRatingList)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []models.PersonalRating) error); ok {
		r0 = rf(entryID, PersonalRatingList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePersonalRating provides a mock function with given fields: e
func (_m *RepositoryI) CreatePersonalRating(e *models.PersonalRating) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.PersonalRating) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteEntryPersonalRatings provides a mock function with given fields: entryID
func (_m *RepositoryI) DeleteEntryPersonalRatings(entryID uint64) error {
	ret := _m.Called(entryID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(entryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeletePersonalRating provides a mock function with given fields: id
func (_m *RepositoryI) DeletePersonalRating(id uint64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetEntryPersonalRatings provides a mock function with given fields: entryID
func (_m *RepositoryI) GetEntryPersonalRatings(entryID uint64) ([]*models.PersonalRating, error) {
	ret := _m.Called(entryID)

	var r0 []*models.PersonalRating
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*models.PersonalRating, error)); ok {
		return rf(entryID)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*models.PersonalRating); ok {
		r0 = rf(entryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PersonalRating)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(entryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPersonalRating provides a mock function with given fields: id
func (_m *RepositoryI) GetPersonalRating(id uint64) (*models.PersonalRating, error) {
	ret := _m.Called(id)

	var r0 *models.PersonalRating
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*models.PersonalRating, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *models.PersonalRating); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PersonalRating)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserPersonalRatings provides a mock function with given fields: userID
func (_m *RepositoryI) GetUserPersonalRatings(userID uint64) ([]*models.PersonalRating, error) {
	ret := _m.Called(userID)

	var r0 []*models.PersonalRating
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*models.PersonalRating, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*models.PersonalRating); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PersonalRating)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateEntryPersonalRatings provides a mock function with given fields: entryID, PersonalRatingList
func (_m *RepositoryI) UpdateEntryPersonalRatings(entryID uint64, PersonalRatingList []models.PersonalRating) error {
	ret := _m.Called(entryID, PersonalRatingList)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64, []models.PersonalRating) error); ok {
		r0 = rf(entryID, PersonalRatingList)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePersonalRating provides a mock function with given fields: e
func (_m *RepositoryI) UpdatePersonalRating(e *models.PersonalRating) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.PersonalRating) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepositoryI interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryI creates a new instance of RepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryI(t mockConstructorTestingTNewRepositoryI) *RepositoryI {
	mock := &RepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
