// Code generated by mockery v2.23.2. DO NOT EDIT.

package mocks

import (
	models "github.com/SerafimKuzmin/sd/src/models"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryI is an autogenerated mock type for the RepositoryI type
type RepositoryI struct {
	mock.Mock
}

// CreateFilm provides a mock function with given fields: g
func (_m *RepositoryI) CreateFilm(g *models.Film) error {
	ret := _m.Called(g)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Film) error); ok {
		r0 = rf(g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFilm provides a mock function with given fields: id
func (_m *RepositoryI) DeleteFilm(id uint64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFilm provides a mock function with given fields: id
func (_m *RepositoryI) GetFilm(id uint64) (*models.Film, error) {
	ret := _m.Called(id)

	var r0 *models.Film
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (*models.Film, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint64) *models.Film); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Film)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserFilms provides a mock function with given fields: userID
func (_m *RepositoryI) GetUserFilms(userID uint64) ([]*models.Film, error) {
	ret := _m.Called(userID)

	var r0 []*models.Film
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) ([]*models.Film, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) []*models.Film); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Film)
		}
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateFilm provides a mock function with given fields: g
func (_m *RepositoryI) UpdateFilm(g *models.Film) error {
	ret := _m.Called(g)

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Film) error); ok {
		r0 = rf(g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRepositoryI interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepositoryI creates a new instance of RepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepositoryI(t mockConstructorTestingTNewRepositoryI) *RepositoryI {
	mock := &RepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
